server:
  port: 8888
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: SpringSecurity
            client-secret: 2rjV4AuK2LLzgX3i8pQQntdFFnAE4trB
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/microservices/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/microservices/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/microservices/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/realms/microservices/protocol/openid-connect/certs
            user-name-attribute: preferred_username
