 server:
   port: 9999 # Порт, на котором будет работать Config Server

 spring:
   application:
     name: CONFIG-SERVER # Название приложения
   cloud:
     config:
       server:
         git:
           uri: git@github.com:Anton-Beschastnov/AppConfigurationServer.git # URL репозитория с конфигурацией, SSH

#   git@github.com — это стандартный SSH-хост для подключения к GitHub.
#   Он используется для работы с репозиториями через SSH.
# username — это владелец репозитория:
#   Если репозиторий находится в вашем аккаунте GitHub, то здесь указывается ваш логин.
#   Если репозиторий принадлежит организации, указывается имя организации.
#   config-repo — имя репозитория, в котором хранятся файлы конфигурации.




 #           username: your-git-username # Имя пользователя для репозитория (если требуется авторизация)
#           password: your-git-password # Пароль или токен для репозитория (если требуется авторизация)
#           search-paths: # Дополнительные пути в репозитории
#             - configs
#           clone-on-start: true # Клонировать репозиторий при старте
#       fail-fast: true # Немедленно завершить работу, если конфигурация недоступна