
spring:
  cloud:
    gateway:
      routes:
        - id: contacts-service
          uri: lb://CONTACTS-SERVICE
          predicates:
            - Path=/api/contact/**
          filters:
            - AuthenticationFilter

        - id: phone-code-service
          uri: lb://PHONE-CODE-SERVICE
          predicates:
            - Path=/api/phone/code/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**
