resilience4j:
  circuitbreaker:
    instances:
      phone_code_service:
        failureRateThreshold: 50 # Порог неудачных попыток, после которого происходит открытие цепи, в процентах от slidingWindowSize
        automaticTransitionFromOpenToHalfOpenEnabled: true # разрешаем автоматически переходить в полуоткрытый режим(Fallback метод работает) по истечении waitDurationInOpenState
        waitDurationInOpenState: 10s
        slidingWindowType: COUNT_BASED # окно анализа, когда   Circuit Breaker переходить в  Open State,
        slidingWindowSize: 2 # анализируй окно из 2 запросов и если 50% из них ошибочны переходи в Open State
        minimumNumberOfCalls: 1 # минимальное кол-во запросов при котором Circuit Breaker  разрешается переходить в Open
        eventConsumerBufferSize: 10 # настройка для актуатора, сохраняй 10 ивенов в память
        registerHealthIndicator: true #  настройка для актуатора, регистрируй ивент
        permittedNumberOfCallsInHalfOpenState: 3 # максимум запросов в Half-Open

#В состоянии Closed:
#  Circuit Breaker отслеживает последние slidingWindowSize вызовов.
#  Если хотя бы 50% из них завершились ошибкой, он переходит в состояние Open, параметр failureRateThreshold - %.
#  slidingWindowType, slidingWindowSize можно указать время и тогда параметр failureRateThreshold будет указывать на % запросов, которые легли за это время
#В состоянии Open:
#  Circuit Breaker блокирует все вызовы на waitDurationInOpenState секунд.
#  automaticTransitionFromOpenToHalfOpenEnabled: true -  разрешаем автоматически переходить в полуоткрытый(Half-Open)
#    режим(в это время работает Fallback метод) по истечении waitDurationInOpenState
#После истечения waitDurationInOpenState секунд:
#  Circuit Breaker переходит в состояние Half-Open и пропускает до permittedNumberOfCallsInHalfOpenState вызовов:
#  Если все permittedNumberOfCallsInHalfOpenState вызовов успешны — переключается обратно в Closed.
#  Если хотя бы один вызов завершился сбоем — возвращается в Open.
#
#  Circuit Breaker не будет сразу реагировать на отказы,
#  пока общее количество вызовов не достигнет значения, указанного в minimumNumberOfCalls.
#  Это помогает избежать ложных срабатываний,
#  особенно если вызовов мало и даже одна ошибка может существенно повлиять на процент отказов.